modLoader       = "javafml"
loaderVersion   = "${forge_loader_version_range}"
issueTrackerURL = "${mod_url}/issues"
license         = "${license}"

[[mods]]
  modId       = "${mod_id}"
  version     = "${version}"
  displayName = "${mod_name}"
  displayURL  = "${mod_url}"
  authors     = "${mod_author}"
  logoFile    = "assets/${mod_id}/icon.png"
  description = '''${description}'''

[[dependencies.${mod_id}]]
  modId        = "minecraft"
  mandatory    = true
  versionRange = "${minecraft_version_range}"
  ordering     = "NONE"
  side         = "BOTH"

[[dependencies.${mod_id}]]
  modId        = "forge"
  mandatory    = true
  versionRange = "${forge_version_range}"
  ordering     = "AFTER"
  side         = "BOTH"

[[dependencies.${mod_id}]]
  modId        = "jade"
  mandatory    = false
  versionRange = "${jade_version_range}"
  ordering     = "NONE"
  side         = "BOTH"
